openapi: 3.0.0
info:
  title: Cryptocurrency Tracker API
  description: API for tracking cryptocurrency prices, market caps, and calculating statistical metrics
  version: 1.0.0
  contact:
    name: API Support
    email: support@cryptotracker.com

servers:
  - url: http://localhost:8000/api/v1
    description: Development server
  - url: https://api.cryptotracker.com
    description: Production server

tags:
  - name: Statistics
    description: Endpoints for retrieving cryptocurrency statistics
  - name: Analysis
    description: Endpoints for analyzing cryptocurrency data

components:
  schemas:
    Error:
      type: object
      properties:
        error:
          type: string
          description: Error message
      required:
        - error

    CryptoStats:
      type: object
      properties:
        price:
          type: number
          format: float
          description: Current price in USD
          example: 40000
        marketCap:
          type: number
          format: float
          description: Market capitalization in USD
          example: 800000000
        24hChange:
          type: number
          format: float
          description: 24-hour price change percentage
          example: 3.4
      required:
        - price
        - marketCap
        - 24hChange

    PriceDeviation:
      type: object
      properties:
        deviation:
          type: number
          format: float
          description: Standard deviation of price
          example: 4082.48
      required:
        - deviation

  parameters:
    CoinParameter:
      name: coin
      in: query
      required: true
      schema:
        type: string
        enum: [bitcoin, matic-network, ethereum]
      description: Cryptocurrency identifier
      example: bitcoin

paths:
  /stats:
    get:
      tags:
        - Statistics
      summary: Get latest cryptocurrency statistics
      description: Returns the current price, market cap, and 24-hour change for the specified cryptocurrency
      operationId: getCryptoStats
      parameters:
        - $ref: "#/components/parameters/CoinParameter"
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CryptoStats"
        "400":
          description: Invalid coin parameter
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /deviation:
    get:
      tags:
        - Analysis
      summary: Get price standard deviation
      description: Calculates the standard deviation of price for the last 100 records of the specified cryptocurrency
      operationId: getPriceDeviation
      parameters:
        - $ref: "#/components/parameters/CoinParameter"
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PriceDeviation"
        "400":
          description: Invalid coin parameter
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
